### ISSUE TITLE
Handshake errors

### ISSUE THREAD

**Issue by ngjermundshaug** [alexandruc/SimpleHttpsClient#1]
Using Boost 1.60 and OpenSSL 1.0.2e - and I keep getting these handshake errors when I try to make a GET towards e.g. https://www.thawte.com and https://www.geotrust.com

```
Resolve OK
Connect OK
Verifying /C=US/O=GeoTrust Inc./CN=GeoTrust Extended Validation SHA256 SSL CA
Handshake failed: certificate verify failed


Resolve OK
Connect OK
Verifying /C=US/O=thawte, Inc./CN=thawte Extended Validation SHA256 SSL CA
Handshake failed: certificate verify failed
```

Is it because OpenSSL is unable to access the trusted root certs in Windows 10?

**Comment by alexandruc** [comment]
Try to do the request with the curl command line:
curl -v https://www.geotrust.com

If that fails, you may have some certificate problem on your machine.

**Comment by alexandruc** [comment]
no answer -> problem must be solved

**Comment by ngjermundshaug** [comment]
Sorry for the late reply.

Please see the accepted answer here: http://stackoverflow.com/questions/15558177/boost-asio-https-request-giving-certificate-verify-failed-error

For me, the problem was that boost/openssl is unable to find any root certificates - so it didn't get preverified - and it failed.

I got it working by making the method **verify_certificate** actually verify the certificate - and not just returning the **preverified** parameter that is sent in. The verification is done against Mozilla's PEM that contains all common CA's - https://curl.haxx.se/ca/cacert.pem.



    bool verify_certificate(bool preverified, boost::asio::ssl::verify_context& ctx)
	{
		// The verify callback can be used to check whether the certificate that is
		// being presented is valid for the peer. For example, RFC 2818 describes
		// the steps involved in doing this for HTTPS. Consult the OpenSSL
		// documentation for more details. Note that the callback is called once
		// for each certificate in the certificate chain, starting from the root
		// certificate authority.

		// In this example we will simply print the certificate's subject name.
		char subject_name[256];
		X509* cert = X509_STORE_CTX_get_current_cert(ctx.native_handle());
		X509_NAME_oneline(X509_get_subject_name(cert), subject_name, 256);
		std::cout << "Verifying " << subject_name << "\n";

		auto store_path = "c:\\temp\\";
		X509_STORE *s = X509_STORE_new();
		if (s == NULL) {
			fprintf(stderr, "unable to create new X509 store.\n");
			return false;
		}
		int rc = X509_STORE_load_locations(s, NULL, store_path);
		if (rc != 1) {
			fprintf(stderr, "unable to load certificates at %s to store\n", store_path);
			X509_STORE_free(s);
			return false;
		}

		X509_STORE_CTX *ctx2 = X509_STORE_CTX_new();
		if (!ctx2) {
			fprintf(stderr, "unable to create STORE CTX\n");
			return -1;
		}
		if (X509_STORE_CTX_init(ctx2, s, cert, NULL) != 1) {
			fprintf(stderr, "unable to initialize STORE CTX.\n");
			X509_STORE_CTX_free(ctx2);
			return -1;
		}
		int rc2 = X509_verify_cert(ctx2);
		X509_STORE_CTX_free(ctx2);
		return rc2 == 1;
	}
