### ISSUE TITLE
Can this be adapted for ASIO Standalone?

### ISSUE THREAD

**Issue by naychrist** [alexandruc/SimpleHttpsClient#2]
Hi there,
thanks for the informative blog post and this sample. I am needing to make a HTTPS POST request and wanted to start with your example. However, the framework I use (http://libcinder.org) has moved from boost asio to standalone asio. I have changed the `placeholder` and `error_code` types so that it compiles but I get some `EXC_BAD_ACCESS` errors that seem to be related to callbacks. Was just wondering if you had any advice/experience here? My adaptation of your code is here:
https://github.com/codeoncanvas/coc-openssl/blob/master/ci-samples/HttpsClient/src/SimpleHttpsClient.h

**Comment by alexandruc** [comment]
I have no experience with stand alone asio. I don't intend to make this example work with anything other than boost::asio. You can try to find an example of stand alone asion https client. I'm sure there are plenty.
