### ISSUE TITLE
OMG. How could asio be so long? I can finish a https client within 2 lines.

### ISSUE THREAD

**Issue by expnkx** [alexandruc/SimpleHttpsClient#4]
https://github.com/expnkx/fast_io/blob/master/examples/0026.custom_device/win32_internet/win32_internet.cc

**Comment by alexandruc** [comment]
Ever heard of syntactic sugar? How many lines are generated for those 2 lines of yours?
The purpose of asio is to give fine grained control.

**Comment by expnkx** [comment]
> Ever heard of syntactic sugar? How many lines are generated for those 2 lines of yours?
> The purpose of asio is to give fine grained control.

LOL. Is this an out of season April fools joke? ASIO library generates at least 4x larger binary size than this library. How many lines of code of ASIO are generated for you?

**Comment by expnkx** [comment]
> Ever heard of syntactic sugar? How many lines are generated for those 2 lines of yours?
> The purpose of asio is to give fine grained control.

TBH, I think ASIO library is one of the worst libraries since what it does is just to recreate what iostream is doing here but only part of it so you have a compatiblity issue.
